### ISSUE TITLE
Melsa / Renelle dps isn’t correct?

### ISSUE THREAD

**Issue by ghost** [b1ueb1ues/b1ueb1ues.github.io#29]
1. Renelle and Melsa are both fire dagger that share the exact same base str (452) but Melsa have 3 more strength on the dps sim.
![4B43A1F8-B8C6-4696-80D3-1B40B80974FD](https://user-images.githubusercontent.com/27050620/61457507-03c86300-a99b-11e9-800d-08b39484aad7.jpeg)
![68893D45-4DF0-4908-A599-211F59F79CF0](https://user-images.githubusercontent.com/27050620/61457509-03c86300-a99b-11e9-951b-76f38abdfd68.jpeg)

2. As mentioned above, Melsa and Renelle share the same base stats and effectively the same passive since physian bane doesn’t count, so they should share the same attack data. However, Melsa have lower normal damage but more force strike damage (for example in the 60 seconds version) which shouldn’t happen, since renelle have higher sp cost for both of her skill so she is more likely to do more force strike if following the “5c+3fs dagger combo” listed on the website.
![C84ED9F9-8723-428C-80A9-764BBFBD614C](https://user-images.githubusercontent.com/27050620/61457740-910bb780-a99b-11e9-8364-6acfe9775027.png)
![71C5CBA7-A2BC-49DE-973C-AC8BD43FACFD](https://user-images.githubusercontent.com/27050620/61457741-91a44e00-a99b-11e9-86b0-c48423b75334.png)

3. In both 120 seconds version and 180 seconds version, Melsa mysteriously have a few less damage than Renelle in her skill 3 listed while they share the same base strength, effective critical rate and damage. This shouldn’t be the problem of renelle getting an extra s3 too since if that is the case the number will have a larger difference.
![AEAC9B72-3986-45DC-BEF3-5E4B47954508](https://user-images.githubusercontent.com/27050620/61458091-5e15f380-a99c-11e9-93dd-220f0b9aa68c.png)
![0367751A-1E4D-4A3A-897A-F214C89A98CE](https://user-images.githubusercontent.com/27050620/61458093-5e15f380-a99c-11e9-8804-0103d6b36816.png)
![C161DF33-0A65-4A0C-82E9-989C52382E22](https://user-images.githubusercontent.com/27050620/61458095-5e15f380-a99c-11e9-89d7-a3e15effdd74.png)
![05C1F971-ED5D-4B71-849B-DBD655B5A6B9](https://user-images.githubusercontent.com/27050620/61458096-5eae8a00-a99c-11e9-99ae-fa6aa8963301.png)

**Comment by qwewqa** [comment]
1. Melsa is input as having 453 str instead of 452 str. This is probably a mistake.

2. 180s data for them is
```
=======================
1758 , Melsa (str: 2886) [RR+FoG] ;<hp70 & hit15> ;
-----------------------
dmgsum     | {'x': 115544, 's': 189303, 'total': 316876, 'fs': 12029, 'others': 0}
skill_stat | {'s3': '7795 *6 = 46771', 's2': '5291 *8 = 42334', 's1': '5893 *17 = 100196'}
x_stat     | {'x1': 1, 'fs': 14, 'x5': 38}
=======================
1785(0.01) , Renelle (str: 2883) [RR+FoG] ;<hp70 & hit15> ;
-----------------------
dmgsum     | {'x': 122743, 's': 185781, 'total': 321470, 'fs': 12945, 'others': 0}
skill_stat | {'s3': '7911 *6 = 47470', 's2': '4559 *9 = 41033', 's1': '5404 *18 = 97277'}
x_stat     | {'x2': 1, 'fs': 15, 'x5': 40}
```
Your claim is not necessarily true because the sp costs do not matter as much as how they align in practice. Melsa has a slightly higher tendency in the current sim durations to use a skill after fs instead of c5. Both only use skills on 5fs or 5c. This is not necessarily the best rotation, but it is the best known.

3. The slightly higher s3 damage on Renelle is due to her s2 def down which will increase the damage of some skill uses.

**Comment by MsNyara** [comment]
Regardless the rotation, Melsa's S1 and S2 have the fatal flaw of sharing a very high frame duration without a higher enough mod to make up for it, a little bit what Ezelith suffers from her S1.

Melsa's S1 deals 2490 DPS and her S2 deals 2190 DPS, among the lowest in the game.

Renelle's S1 deals 2754 DPS and her S2 deals 2381 DPS + 30% chance to 5% defense down for 10s.

About the SP costs: It will always rely on the rotation used, I'm testing out a new rotation for Melsa and SP costs does not vary anything with Renelle aside forcing her to C4FS+C4FS+C1 instead C4FS+C5 once in a one minute long rotation, which just ticks her a few points down. In the current rotation used in the simulation Renelle is over-punished by having to repeat something like this on a shorter rotation.

S2 Def Down Impact: It is about 0.80% more DPS on average and gives her very petty team buff since it affects all the team.

In the bright side, Melsa has her bane where she excels a lot, and having a high skill duration is not necessary bad when it comes to i-frame or mob smashing, which Melsa also does better, Melsa's skills are also better when it comes to recover back combo count. Plus Sleep Res is a lot better than Curse Res. Those points are not considered in the simulation.

**Comment by b1ueb1ues** [comment]
wrong atk was fixed
